-- Languages backup
-- Generated: 2025-12-27 21:08:00
-- Total rows: 631

TRUNCATE TABLE languages;

INSERT INTO languages (id, `key`, ko, tw, location) VALUES (1, 'Dashboard', '대시보드', '儀表板', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (2, 'Members', '회원', '會員', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (3, 'Groups', '그룹', '群組', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (4, 'Menus', '메뉴', '選單', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (5, 'Boards', '게시판', '討論板', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (6, 'Files', '파일', '檔案', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (7, 'Editor Images', '에디터 이미지', '編輯器圖片', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (8, 'Board Attachments', '게시판 첨부파일', '討論板附件', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (9, 'Languages', '언어 설정', '語言設定', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (10, 'Settings', '설정', '設定', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (11, 'Profile', '프로필', '個人資料', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (12, 'Logout', '로그아웃', '登出', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (13, 'Language Management', '언어 관리', '語言管理', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (14, 'Cleanup Unused', '미사용 정리', '清理未使用', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (15, 'Translation Keys', '번역 키', '翻譯鍵', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (16, 'Key', '키', '鍵', 'sitemanager.languages.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (17, 'Actions', '작업', '操作', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (18, 'Enter translation', '번역 입력', '輸入翻譯', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (19, 'Translation saved successfully', '번역이 성공적으로 저장되었습니다', '翻譯已成功保存', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (20, 'Error saving translation', '번역 저장 중 오류가 발생했습니다', '保存翻譯時出錯', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (21, 'Are you sure you want to delete this language key?', '이 언어 키를 삭제하시겠습니까?', '您確定要刪除此語言鍵嗎？', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (22, 'This will remove unused language keys. Are you sure?', '사용하지 않는 언어 키를 제거합니다. 계속하시겠습니까?', '這將刪除未使用的語言鍵。您確定嗎？', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (23, 'Total', '총계', '總計', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (24, 'Save', '저장', '儲存', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (25, 'Delete', '삭제', '刪除', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.groups.index,sitemanager.boards.index,sitemanager.comments.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (26, 'Processing', '처리 중', '處理中', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (27, 'Cleanup completed', '정리 완료', '清理完成', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (28, 'Error during cleanup', '정리 중 오류', '清理時發生錯誤', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (29, 'English', '영어', '英語', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (30, 'Total Members', '총 회원', '總會員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (31, 'Active Members', '활성 회원', '活躍會員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (32, 'Total Groups', '총 그룹', '總群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (33, 'Total Menus', '총 메뉴', '總選單', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (34, 'Recent Members', '최근 회원', '最近會員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (35, 'View All', '모두 보기', '檢視全部', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (36, 'Name', '이름', '名稱', 'sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (37, 'Email', '이메일', '電子郵件', 'sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (38, 'Status', '상태', '狀態', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.boards.index,sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (39, 'Join Date', '가입일', '加入日期', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (40, 'Edit', '편집', '編輯', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (41, 'Active', '활성', '啟用', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.boards.index,sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (42, 'Quick Actions', '빠른 작업', '快速操作', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (43, 'Add New Member', '새 회원 추가', '新增會員', 'sitemanager.members.index,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (44, 'Add New Menu', '새 메뉴 추가', '新增選單', 'sitemanager.dashboard,sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (45, 'System Settings', '시스템 설정', '系統設定', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (46, 'System Information', '시스템 정보', '系統資訊', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (47, 'Laravel Version', 'Laravel 버전', 'Laravel 版本', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (48, 'PHP Version', 'PHP 버전', 'PHP 版本', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (49, 'Environment', '환경', '環境', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (50, 'Server Time', '서버 시간', '伺服器時間', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (51, 'MySQL Time', 'MySQL 시간', 'MySQL 時間', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (52, 'MySQL Version', 'MySQL 버전', 'MySQL 版本', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (53, 'Timezone', '시간대', '時區', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (54, 'Recent Member Trends', '최근 회원 동향', '最近會員趨勢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (55, 'This Month', '이번 달', '本月', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (56, 'Last Month', '지난달', '上個月', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (57, 'Growth Rate', '성장률', '成長率', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (58, 'Member Group Distribution', '회원 그룹 분포', '會員群組分佈', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (59, 'Configuration', '구성', '配置', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (60, 'Type', '유형', '類型', 'sitemanager.files.board-attachments,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (61, 'Value', '값', '值', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (62, 'Action', '작업', '操作', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (63, 'Disabled', '비활성', '停用', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (64, 'System', '시스템', '系統', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (65, 'Enabled', '활성', '啟用', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (66, 'New Key', '새 키', '新鍵', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (67, 'New Value', '새 값', '新值', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (68, 'New', '새로운', '新增', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (69, 'Save Changes', '변경 사항 저장', '儲存變更', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (70, 'Information', '정보', '資訊', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (71, 'Configuration Types', '구성 유형', '配置類型', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (72, 'System environment variables (synced with .env)', '시스템 환경 변수 (.env와 동기화됨)', '系統環境變數（與 .env 同步）', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (73, 'System boolean settings (synced with .env)', '시스템 불린 설정 (.env와 동기화됨)', '系統布林設定（與 .env 同步）', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (74, 'Application text settings', '애플리케이션 텍스트 설정', '應用程式文字設定', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (75, 'Application boolean settings', '애플리케이션 불린 설정', '應用程式布林設定', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (76, 'Usage Notes', '사용 안내', '使用說明', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (77, 'Settings with', '설정과 함께', '設定與', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (78, 'prefix will update your .env file', '접두사는 .env 파일을 업데이트합니다', '前綴將更新您的 .env 檔案', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (79, 'settings are protected and cannot be deleted', '설정이 보호되어 삭제할 수 없습니다', '設定受保護且無法刪除', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (80, 'Key names should use alphanumeric characters, underscores, and hyphens only', '키 이름은 영숫자, 밑줄, 하이픈만 사용해야 합니다', '鍵名稱應僅使用字母數字、底線和連字符', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (81, 'Boolean values are stored as \'true\' or \'false\' strings', '불린 값은 \'true\' 또는 \'false\' 문자열로 저장됩니다', '布林值以 \'true\' 或 \'false\' 字串儲存', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (82, 'Changes take effect immediately after saving', '변경 사항은 저장 후 즉시 적용됩니다', '變更將在儲存後立即生效', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (83, 'Other Actions', '기타 작업', '其他操作', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (84, 'Reset Configuration', '설정 초기화', '重置配置', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (85, 'Reset Resources', '리소스 초기화', '重置資源', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (86, 'Delete Setting', '설정 삭제', '刪除設定', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (87, 'Are you sure you want to delete this setting?', '이 설정을 삭제하시겠습니까?', '您確定要刪除此設定嗎？', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (88, 'Cancel', '취소', '取消', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (89, 'Undo delete', '삭제 취소', '取消刪除', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (90, 'Are you sure you want to reset all settings to default values? User-added settings will be deleted.', '모든 설정을 기본값으로 초기화하시겠습니까? 사용자가 추가한 설정은 삭제됩니다.', '您確定要將所有設定重置為預設值嗎？使用者新增的設定將被刪除。', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (91, 'Reset', '초기화', '重置', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (92, 'Are you sure you want to reset all resource files? CSS/JS cache will be deleted and regenerated.', '모든 리소스 파일을 초기화하시겠습니까? CSS/JS 캐시가 삭제되고 다시 생성됩니다.', '您確定要重置所有資源檔案嗎？CSS/JS 快取將被刪除並重新生成。', 'sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (93, 'Search', '검색', '搜尋', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (94, 'Add', '추가', '新增', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (95, 'Create', '생성', '建立', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (96, 'Update', '업데이트', '更新', 'sitemanager.boards.edit,sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (97, 'Confirm', '확인', '確認', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (98, 'Yes', '예', '是', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (99, 'No', '아니오', '否', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (100, 'Loading', '로딩 중', '載入中', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (101, 'Success', '성공', '成功', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (102, 'Error', '오류', '錯誤', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (103, 'Warning', '경고', '警告', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (104, 'Description', '설명', '描述', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (105, 'Created', '작성일', '建立日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (106, 'Updated', '수정일', '修改日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (107, 'Inactive', '비활성', '停用', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (108, 'No data found', '데이터가 없습니다', '找不到資料', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (109, 'Previous', '이전', '上一頁', 'sitemanager.files.editor-images,sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (110, 'Next', '다음', '下一頁', 'sitemanager.files.editor-images,sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (111, 'Home', '홈', '首頁', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (112, 'Back', '뒤로', '返回', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (113, 'Close', '닫기', '關閉', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (114, 'Show', '보기', '顯示', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (115, 'Hide', '숨기기', '隱藏', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (116, 'All', '전체', '全部', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (117, 'None', '없음', '無', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (118, 'Optional', '선택사항', '可選', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (119, 'Required', '필수', '必填', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (120, 'Members List', '회원 목록', '會員列表', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (121, 'Search by name, username, or email...', '이름, 사용자명 또는 이메일로 검색...', '依姓名、使用者名稱或電子郵件搜尋...', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (122, 'All Levels', '모든 레벨', '所有等級', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (123, 'All Groups', '모든 그룹', '所有群組', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (124, 'All Status', '모든 상태', '所有狀態', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (125, 'Deleted', '삭제됨', '已刪除', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (126, 'ID', 'ID', 'ID', 'sitemanager.members.index,sitemanager.groups.index,sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (127, 'Photo', '사진', '照片', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (128, 'Username', '사용자명', '使用者名稱', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (129, 'Level', '레벨', '等級', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (130, 'Admin', '관리자', '管理員', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (131, 'Edit Member', '회원 편집', '編輯會員', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (132, 'Permanent Delete Confirmation', '영구 삭제 확인', '永久刪除確認', 'sitemanager.members.index,sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (133, 'Are you sure you want to permanently delete this member? This action cannot be undone.', '이 회원을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.', '您確定要永久刪除此會員嗎？此操作無法復原。', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (134, 'Permanent Delete', '영구 삭제', '永久刪除', 'sitemanager.members.index,sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (135, 'Member Delete Confirmation', '회원 삭제 확인', '會員刪除確認', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (136, 'Are you sure you want to delete this member?', '이 회원을 삭제하시겠습니까?', '您確定要刪除此會員嗎？', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (137, 'activate', '활성화', '啟用', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (138, 'deactivate', '비활성화', '停用', 'sitemanager.members.index,sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (139, 'Are you sure you want to', '정말로', '您確定要', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (140, 'this member?', '이 회원을 하시겠습니까?', '此會員嗎？', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (141, 'Click to', '클릭하여', '點擊以', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (142, 'Success!', '성공!', '成功！', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (143, 'Error!', '오류!', '錯誤！', 'sitemanager.members.index,sitemanager.files.editor-images,sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (144, 'Failed to update member status.', '회원 상태 업데이트에 실패했습니다.', '更新會員狀態失敗。', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (145, 'Network error occurred.', '네트워크 오류가 발생했습니다.', '發生網路錯誤。', 'sitemanager.members.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (146, 'Root user\'s username cannot be changed.', '최고 관리자의 사용자명은 변경할 수 없습니다.', '根使用者的使用者名稱無法變更。', 'sitemanager.members.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (147, 'Title', '직책', '職稱', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (148, 'Title or honorific (e.g., Mr., Mrs., etc.)', '직책이나 경칭 (예: 씨, 님 등)', '職稱或敬語（例如：先生、女士等）', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (149, 'Phone', '전화번호', '電話', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (150, 'Profile Photo', '프로필 사진', '個人照片', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (151, 'Upload a new profile photo (JPEG, PNG, GIF). Max size: 2MB', '새 프로필 사진을 업로드하세요 (JPEG, PNG, GIF). 최대 크기: 2MB', '上傳新的個人照片（JPEG、PNG、GIF）。最大大小：2MB', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (152, 'Member Level', '회원 레벨', '會員等級', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (153, 'Account Status', '계정 상태', '帳戶狀態', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (154, 'Active Account', '활성 계정', '啟用帳戶', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (155, 'When deactivated, the member cannot log in.', '비활성화되면 회원이 로그인할 수 없습니다.', '停用時，會員無法登入。', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (156, 'No groups available.', '사용 가능한 그룹이 없습니다.', '沒有可用的群組。', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (157, 'Change Password (Optional)', '비밀번호 변경 (선택사항)', '變更密碼（可選）', 'sitemanager.members.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (158, 'Leave the password fields empty if you don\'t want to change the password.', '비밀번호를 변경하지 않으려면 비밀번호 필드를 비워두세요.', '如果您不想變更密碼，請將密碼欄位留空。', 'sitemanager.members.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (159, 'New Password', '새 비밀번호', '新密碼', 'sitemanager.members.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (160, 'Confirm Password', '비밀번호 확인', '確認密碼', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (161, 'Update Member', '회원 수정', '更新會員', 'sitemanager.members.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (162, 'Please select a valid image file.', '유효한 이미지 파일을 선택해주세요.', '請選擇有效的圖片檔案。', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (163, 'File size must be less than 2MB.', '파일 크기는 2MB 미만이어야 합니다.', '檔案大小必須小於 2MB。', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (164, 'Are you sure you want to remove the current profile photo?', '현재 프로필 사진을 제거하시겠습니까?', '您確定要移除目前的個人照片嗎？', 'sitemanager.members.edit,sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (165, 'Username must be unique.', '사용자명은 고유해야 합니다.', '使用者名稱必須是唯一的。', 'sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (166, 'Password', '비밀번호', '密碼', 'sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (167, 'Create Member', '회원 생성', '建立會員', 'sitemanager.members.create');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (168, 'Search by key or translation text...', '키 또는 번역 텍스트로 검색...', '依鍵值或翻譯文字搜尋...', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (169, 'All Keys', '모든 키', '所有鍵值', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (170, 'Fully Translated', '완전 번역됨', '完全翻譯', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (171, 'Partially Translated', '부분 번역됨', '部分翻譯', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (172, 'Untranslated', '번역되지 않음', '未翻譯', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (173, 'Groups List', '그룹 목록', '群組列表', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (174, 'Add New Group', '새 그룹 추가', '新增群組', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (175, 'Search by name or description...', '이름 또는 설명으로 검색...', '依名稱或說明搜尋...', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (176, 'Clear', '지우기', '清除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (177, 'Created Date', '생성일', '建立日期', 'sitemanager.groups.index,sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (178, 'Restore Group', '그룹 복구', '恢復群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (179, 'Edit Group', '그룹 편집', '編輯群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (180, 'Delete Group', '그룹 삭제', '刪除群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (181, 'No groups found.', '그룹을 찾을 수 없습니다.', '找不到群組。', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (182, 'Are you sure you want to permanently delete this group? This action cannot be undone.', '이 그룹을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.', '您確定要永久刪除此群組嗎？此操作無法復原。', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (183, 'Group Delete Confirmation', '그룹 삭제 확인', '群組刪除確認', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (184, 'Are you sure you want to delete this group?', '이 그룹을 삭제하시겠습니까?', '您確定要刪除此群組嗎？', 'sitemanager.groups.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (185, 'Create Group', '그룹 생성', '建立群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (186, 'Back to List', '목록으로 돌아가기', '回到列表', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (187, 'Group Name', '그룹명', '群組名稱', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (188, 'Current Members', '현재 회원', '目前成員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (189, 'Available Members', '추가 가능한 회원', '可用成員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (190, 'No members in this group', '이 그룹에 회원이 없습니다', '此群組沒有成員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (191, 'No available members', '추가 가능한 회원이 없습니다', '沒有可用成員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (192, 'Update Group', '그룹 수정', '更新群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (193, 'Menu Management', '메뉴 관리', '選單管理', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (194, 'Rebuild Tree', '트리 재구성', '重建樹狀結構', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (195, 'Drag to reorder. Hold Command (Mac) or Ctrl (Win) while dragging to create a sub-menu.', '드래그하여 순서를 변경하세요. 드래그하는 동안 Command(Mac) 또는 Ctrl(Win)을 누르고 있으면 하위 메뉴를 만들 수 있습니다.', '拖曳以重新排序。拖曳時按住 Command(Mac) 或 Ctrl(Win) 可建立子選單。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (196, 'Invalid Route', '잘못된 라우트', '無效路由', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (197, 'HIDDEN', '숨김', '隱藏', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (198, 'Hidden Menu', '숨겨진 메뉴', '隱藏選單', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (199, 'NO ACCESS', '접근 불가', '無訪問權限', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (200, 'No Access Permission', '접근 권한 없음', '無訪問權限', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (201, 'Drag to reorder menus', '드래그하여 메뉴 순서 변경', '拖曳以重新排序選單', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (202, 'Invalid', '잘못됨', '無效', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (203, 'No menus registered.', '등록된 메뉴가 없습니다.', '沒有註冊的選單。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (204, 'Add Your First Menu', '첫 번째 메뉴 추가', '新增您的第一個選單', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (205, 'Tree Structure Rebuild', '트리 구조 재구성', '樹狀結構重建', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (206, 'Are you sure you want to rebuild the tree structure?', '정말로 트리 구조를 재구성하시겠습니까?', '您確定要重建樹狀結構嗎？', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (207, 'Rebuild', '재구성', '重建', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (208, 'Processing...', '처리 중...', '處理中...', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (209, 'Rebuilding tree structure.', '트리 구조를 재구성하고 있습니다.', '正在重建樹狀結構。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (210, 'Complete!', '완료!', '完成！', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (211, 'Rebuild operation failed.', '재구성 작업이 실패했습니다.', '重建操作失敗。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (212, 'An error occurred during rebuild.', '재구성 중 오류가 발생했습니다.', '重建過程中發生錯誤。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (213, 'Edit Menu', '메뉴 편집', '編輯選單', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (214, 'Menu Information', '메뉴 정보', '選單資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (215, 'Menu Title', '메뉴 제목', '選單標題', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (216, 'Enter a short description', '간단한 설명을 입력하세요', '輸入簡短說明', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (217, 'Optional. This description helps identify the menu\'s purpose and may be used as the SEO description.', '선택사항입니다. 이 설명은 메뉴의 목적을 식별하는 데 도움이 되며 SEO 설명으로 사용될 수 있습니다.', '可選。此說明有助於識別選單的用途，也可用作 SEO 說明。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (218, 'Menu Type', '메뉴 유형', '選單類型', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (219, 'Select menu type', '메뉴 유형을 선택하세요', '選擇選單類型', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (220, 'No language keys found', '언어 키를 찾을 수 없습니다', '找不到語言鍵', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (221, 'Add Image', '이미지 추가', '新增圖片', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (222, 'Upload images for different purposes (thumbnail, header, SEO, etc.)', '다양한 용도의 이미지를 업로드하세요 (썸네일, 헤더, SEO 등)', '為不同目的上傳圖片（縮圖、標題、SEO等）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (223, 'Permissions', '권한', '權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (224, 'Basic Permission', '기본 권한', '基本權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (225, 'Level Permission', '레벨 권한', '等級權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (228, 'Group Permission', '그룹 권한', '群組權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (230, 'Administrator Permission', '관리자 권한', '管理員權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (232, 'All permissions', '모든 권한', '所有權限', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (233, 'Permissions can only be set for existing menus. Save the menu first to configure permissions.', '권한은 기존 메뉴에 대해서만 설정할 수 있습니다. 권한을 구성하려면 먼저 메뉴를 저장하세요.', '權限只能為現有選單設定。請先儲存選單以配置權限。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (234, 'Available Routes', '사용 가능한 라우트', '可用路由', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (235, 'Select a route', '라우트를 선택하세요', '選擇路由', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (236, 'No routes available', '사용 가능한 라우트가 없습니다', '沒有可用的路由', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (237, 'Choose from available Laravel routes above.', '위의 사용 가능한 Laravel 라우트 중에서 선택하세요.', '從上面的可用Laravel路由中選擇。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (238, 'routes found', '개 라우트를 찾았습니다', '找到的路由', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (239, 'The current route', '현재 라우트', '當前路由', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (240, 'no longer exists in the application.', '가 애플리케이션에 더 이상 존재하지 않습니다.', '在應用程式中不再存在。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (241, 'This route may have been removed or renamed. Please select a new route from the list above.', '이 라우트가 제거되었거나 이름이 변경되었을 수 있습니다. 위 목록에서 새 라우트를 선택해주세요.', '此路由可能已被移除或重新命名。請從上面的列表中選擇新路由。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (242, 'Target', '대상', '目標', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (243, 'Please select menu type first.', '먼저 메뉴 타입을 선택해주세요.', '請先選擇選單類型。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (244, 'does not exist.', '가 존재하지 않습니다.', '不存在。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (245, 'This menu will not function properly. Please switch to route type and select a valid route, or change the menu type to URL and provide a full URL.', '이 메뉴는 제대로 작동하지 않습니다. 라우트 타입으로 변경하고 유효한 라우트를 선택하거나, 메뉴 타입을 URL로 변경하고 전체 URL을 제공해주세요.', '此選單將無法正常運作。請切換到路由類型並選擇有效路由，或將選單類型更改為URL並提供完整URL。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (246, 'Parent Menu', '상위 메뉴', '父選單', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (247, 'Root Menu (Creates New Section)', '루트 메뉴 (새 섹션 생성)', '根選單（創建新部分）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (248, 'Select a parent menu to inherit its section, or leave empty to create a new section.', '해당 섹션을 상속할 상위 메뉴를 선택하거나, 비워두어 새 섹션을 만드세요.', '選擇父選單以繼承其部分，或留空以創建新部分。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (249, 'Hidden menus will not be displayed in navigation.', '숨겨진 메뉴는 네비게이션에 표시되지 않습니다.', '隱藏的選單不會在導航中顯示。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (250, 'Menu Images', '메뉴 이미지', '選單圖片', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (251, 'Delete Menu', '메뉴 삭제', '刪除選單', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (252, 'Select Administrator', '관리자 선택', '選擇管理員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (253, 'Search by name or ID...', '이름 또는 아이디로 검색...', '按姓名或ID搜尋...', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (254, 'Please enter search terms.', '검색어를 입력하세요.', '請輸入搜尋詞。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (255, 'Menu Delete Confirmation', '메뉴 삭제 확인', '選單刪除確認', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (256, 'Are you sure you want to delete this menu?', '이 메뉴를 삭제하시겠습니까?', '您確定要刪除此選單嗎？', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (257, 'Search for a route...', '라우트를 검색...', '搜尋路由...', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (258, 'Search for parent menu or leave empty for new section...', '상위 메뉴를 검색하거나 새 섹션을 위해 비워두세요...', '搜尋父選單或留空以創建新部分...', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (259, 'Enter full URL (e.g., https://example.com)', '전체 URL을 입력하세요 (예: https://example.com)', '輸入完整URL（例如：https://example.com）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (260, 'Text menus do not require a target.', '텍스트 메뉴는 대상이 필요하지 않습니다.', '文字選單不需要目標。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (261, 'Selected', '선택됨', '已選擇', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (262, 'No Board Connected', '연결된 게시판 없음', '沒有連接的看板', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (263, 'The board.index route requires a board to be connected to this menu.', 'board.index 라우트는 이 메뉴에 게시판이 연결되어야 합니다.', 'board.index路由需要將看板連接到此選單。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (264, 'Please create a board and connect it to this menu, or this menu will not function properly.', '게시판을 생성하고 이 메뉴에 연결하거나, 이 메뉴가 제대로 작동하지 않을 것입니다.', '請創建看板並將其連接到此選單，否則此選單將無法正常運作。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (265, 'Create New Board', '새 게시판 생성', '建立新看板', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (266, 'Board Connected', '게시판 연결됨', '看板已連接', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (267, 'Board', '게시판', '版面', 'sitemanager.files.editor-images,sitemanager.files.board-attachments,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (268, 'is connected to this menu.', '이 메뉴에 연결되어 있습니다.', '已連接到此選單。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (269, 'This menu will redirect to the board index page when clicked.', '이 메뉴를 클릭하면 게시판 인덱스 페이지로 리디렉션됩니다.', '點擊此選單時將重定向到看板索引頁面。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (270, 'Manage Boards', '게시판 관리', '管理看板', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (271, 'All levels have already been added.', '모든 레벨이 이미 추가되었습니다.', '所有等級都已添加。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (272, 'Please select a level', '레벨을 선택하세요', '請選擇等級', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (273, 'No groups are registered. Please create a group first.', '등록된 그룹이 없습니다. 먼저 그룹을 생성해주세요.', '沒有註冊的群組。請先創建群組。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (274, 'All groups have already been added.', '모든 그룹이 이미 추가되었습니다.', '所有群組都已添加。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (275, 'Please select a group', '그룹을 선택하세요', '請選擇群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (276, 'Group', '그룹', '群組', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (277, 'This level has already been selected. Please select a different level.', '이미 선택된 레벨입니다. 다른 레벨을 선택해주세요.', '此等級已被選擇。請選擇不同的等級。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (278, 'This group has already been selected.', '이미 선택된 그룹입니다.', '此群組已被選擇。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (279, 'This administrator has already been added.', '이미 추가된 관리자입니다.', '此管理員已被添加。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (280, 'Please enter at least 2 characters.', '최소 2글자 이상 입력하세요.', '請輸入至少2個字符。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (281, 'No search results found.', '검색 결과가 없습니다.', '找不到搜尋結果。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (282, 'An error occurred during search.', '검색 중 오류가 발생했습니다.', '搜尋過程中發生錯誤。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (283, 'Remove', '제거', '移除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (284, 'Language updated successfully', '언어가 성공적으로 업데이트되었습니다', '語言已成功更新', 'sitemanager.languages.update');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (285, 'Language deleted successfully', '언어가 성공적으로 삭제되었습니다', '語言已成功刪除', 'sitemanager.languages.destroy');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (287, 'Add Administrator', '관리자 추가', '新增管理員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (289, 'Add Level', '레벨 추가', '新增等級', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (291, 'Board Management', '게시판 관리', '看板管理', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (292, 'Add New Board', '새 게시판 추가', '新增看板', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (293, 'Board Name', '게시판 이름', '看板名稱', 'sitemanager.boards.index,sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (294, 'Slug', '슬러그', '網址代碼', 'sitemanager.boards.index,sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (295, 'Skin', '스킨', '外觀主題', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (296, 'Connected Menu', '연결된 메뉴', '連結選單', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (297, 'Posts', '게시물', '篇文章', 'sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (298, 'Comments', '댓글', '留言', 'sitemanager.boards.index,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (299, 'Pending Comments', '대기 중인 댓글', '待審核留言', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (300, 'Change status?', '상태를 변경하시겠습니까?', '要更改狀態嗎？', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (301, 'Delete this board?', '이 게시판을 삭제하시겠습니까?', '要刪除這個看板嗎？', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (302, 'Warning: All posts and comments will be deleted!', '경고: 모든 게시글과 댓글이 삭제됩니다!', '警告：所有文章和留言都將被刪除！', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (303, 'No boards found', '게시판이 없습니다', '找不到看板', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (304, 'Please create a new board.', '새 게시판을 만들어 주세요.', '請建立新的看板。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (305, 'Create Board', '게시판 생성', '建立看板', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (306, 'Manage pending comments', '대기 중인 댓글 관리', '管理待審核留言', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (307, 'Edit Board', '게시판 편집', '編輯看板', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (308, 'Please correct the following errors:', '다음 오류를 수정해 주세요:', '請修正以下錯誤：', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (309, 'Basic Information', '기본 정보', '基本資訊', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (310, 'Only lowercase letters, numbers, and underscores are allowed', '소문자, 숫자, 밑줄만 허용됩니다', '僅允許小寫字母、數字和底線', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (311, 'Used in URLs and database table names. Only lowercase letters, numbers, and underscores are allowed.', 'URL과 데이터베이스 테이블명에 사용됩니다. 소문자, 숫자, 밑줄만 허용됩니다.', '用於URL和資料庫表格名稱。僅允許小寫字母、數字和底線。', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (312, 'Connect to Menu', '메뉴에 연결', '連結到選單', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (313, 'Select Menu (Optional)', '메뉴 선택 (선택사항)', '選擇選單（可選）', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (314, 'Theme/Skin', '테마/스킨', '主題/外觀', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (315, 'Default', '기본값', '預設', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (316, 'Choose the theme/skin for this board\'s appearance.', '이 게시판의 외관을 위한 테마/스킨을 선택하세요.', '選擇此看板外觀的主題/外觀。', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (317, 'Posts per Page', '페이지당 게시글 수', '每頁文章數', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (318, 'Custom Settings', '사용자 정의 설정', '自訂設定', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (319, 'Add Setting', '설정 추가', '新增設定', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (320, 'Setting key', '설정 키', '設定鍵', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (321, 'Setting value', '설정 값', '設定值', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (322, 'Add custom settings that can be accessed in templates using', '템플릿에서 다음을 사용하여 접근할 수 있는 사용자 정의 설정을 추가합니다', '新增可在模板中使用以下方式存取的自訂設定', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (323, 'Invalid characters found', '잘못된 문자가 발견되었습니다', '發現無效字元', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (324, 'Suggested', '제안', '建議', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (325, 'Uppercase letters are not allowed', '대문자는 허용되지 않습니다', '不允許大寫字母', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (326, 'Try', '시도해보세요', '試試', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (327, 'Spaces are not allowed', '공백은 허용되지 않습니다', '不允許空格', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (328, 'Hyphens are not allowed (use underscores instead)', '하이픈은 허용되지 않습니다 (밑줄을 사용하세요)', '不允許連字號（請使用底線）', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (329, 'Slug is too long (maximum 50 characters)', '슬러그가 너무 깁니다 (최대 50자)', '網址代碼太長（最多50個字元）', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (330, 'Slug should not start or end with underscores', '슬러그는 밑줄로 시작하거나 끝나면 안 됩니다', '網址代碼不應以底線開始或結束', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (331, 'Multiple consecutive underscores are not recommended', '연속된 여러 밑줄은 권장되지 않습니다', '不建議使用多個連續底線', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (332, 'Valid slug format!', '유효한 슬러그 형식입니다!', '有效的網址代碼格式！', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (333, 'Click to use this suggestion', '이 제안을 사용하려면 클릭하세요', '點擊使用此建議', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (334, 'Setting key (e.g., show_name)', '설정 키 (예: show_name)', '設定鍵（例如：show_name）', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (335, 'Setting value (e.g., true, hello world)', '설정 값 (예: true, hello world)', '設定值（例如：true, hello world）', 'sitemanager.boards.edit');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (336, 'Comment Management', '댓글 관리', '留言管理', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (337, 'Approved Comments', '승인된 댓글', '已核准留言', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (338, 'Deleted Comments', '삭제된 댓글', '已刪除留言', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (339, 'Pending', '대기 중', '待審核', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (340, 'Approved', '승인됨', '已核准', 'sitemanager.comments.index,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (341, 'Approve Selected', '선택 항목 승인', '核准選中項目', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (342, 'Delete Selected', '선택 항목 삭제', '刪除選中項目', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (343, 'Restore Selected', '선택 항목 복원', '復原選中項目', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (344, 'Force Delete Selected', '선택 항목 강제 삭제', '強制刪除選中項目', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (345, 'Author', '작성자', '作者', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (346, 'Post', '게시물', '文章', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (347, 'Comment Content', '댓글 내용', '留言內容', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (348, 'Created At', '생성일시', '建立時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (349, 'Deleted Post', '삭제된 게시글', '已刪除文章', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (350, 'Parent', '부모', '父級', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (351, 'Parent deleted', '부모 삭제됨', '父級已刪除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (352, 'replies', '답글', '回覆', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (353, 'Restore', '복원', '復原', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (354, 'Force Delete', '강제 삭제', '強制刪除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (355, 'Approve', '승인', '核准', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (356, 'No comments found matching the criteria.', '조건에 맞는 댓글이 없습니다.', '找不到符合條件的留言。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (357, 'Please select a board.', '게시판을 선택해 주세요.', '請選擇看板。', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (358, 'Are you sure you want to approve this comment?', '이 댓글을 승인하시겠습니까?', '您確定要核准這個留言嗎？', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (359, 'Are you sure you want to permanently delete this comment?', '이 댓글을 영구적으로 삭제하시겠습니까?', '您確定要永久刪除這個留言嗎？', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (360, 'Are you sure you want to restore this comment?', '이 댓글을 복원하시겠습니까?', '您確定要復原這個留言嗎？', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (361, 'Are you sure you want to permanently delete this comment? This action cannot be undone.', '이 댓글을 영구적으로 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.', '您確定要永久刪除這個留言嗎？此操作無法撤銷。', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (362, 'An error occurred.', '오류가 발생했습니다.', '發生錯誤。', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (363, 'A network error occurred.', '네트워크 오류가 발생했습니다.', '發生網路錯誤。', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (364, 'Please select comments to process.', '처리할 댓글을 선택해 주세요.', '請選擇要處理的留言。', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (365, 'permanently delete', '영구 삭제', '永久刪除', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (366, 'Are you sure you want to {action} {count} selected comment(s)?', '선택한 {count}개의 댓글을 {action}하시겠습니까?', '您確定要{action}選中的{count}個留言嗎？', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (367, 'Editor Images Management', '에디터 이미지 관리', '編輯器圖片管理', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (368, 'Images', '이미지', '張圖片', 'sitemanager.files.editor-images,sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (369, 'Usage Status', '사용 상태', '使用狀態', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (370, 'Search by filename...', '파일명으로 검색...', '以檔名搜尋...', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (371, 'Preview', '미리보기', '預覽', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (372, 'Click to view larger', '클릭하여 크게 보기', '點擊查看大圖', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (373, 'Click to download', '클릭하여 다운로드', '點擊下載', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (374, 'View post', '게시물 보기', '查看文章', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (375, 'No Title', '제목 없음', '無標題', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (376, 'Temp ID', '임시 ID', '臨時 ID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (377, 'Reference needs update', '참조 업데이트 필요', '需要更新參考', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (378, 'No Board', '게시판 없음', '無版面', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (379, 'Check actual usage status', '실제 사용 상태 확인', '檢查實際使用狀態', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (380, 'Are you sure you want to delete this image?', '이 이미지를 삭제하시겠습니까?', '確定要刪除此圖片嗎？', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (381, 'No editor images found.', '에디터 이미지가 없습니다.', '沒有找到編輯器圖片。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (382, 'Replace Image', '이미지 교체', '替換圖片', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (383, 'Choose new image', '새 이미지 선택', '選擇新圖片', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (384, 'Max file size: 5MB. Allowed formats: JPG, PNG, GIF, WebP', '최대 파일 크기: 5MB. 허용 형식: JPG, PNG, GIF, WebP', '最大檔案大小：5MB。允許格式：JPG、PNG、GIF、WebP', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (385, 'Image Usage Check', '이미지 사용 여부 확인', '圖片使用狀況檢查', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (386, 'Loading...', '로딩 중...', '載入中...', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (387, 'Mark as Used', '사용됨으로 표시', '標記為已使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (388, 'Mark as Unused', '미사용으로 표시', '標記為未使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (389, 'All Boards', '모든 게시판', '所有版面', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (390, 'Used', '사용됨', '已使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (391, 'Unused', '미사용', '未使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (392, 'Filter', '필터', '篩選', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (393, 'Filename', '파일명', '檔案名稱', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (394, 'Size', '크기', '大小', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (395, 'Upload Date', '업로드 날짜', '上傳日期', 'sitemanager.files.editor-images,sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (396, 'Image Preview', '이미지 미리보기', '圖片預覽', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (397, 'Download', '다운로드', '下載', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (398, 'Not Used', '사용 안됨', '未使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (399, 'Status Mismatch!', '상태 불일치!', '狀態不符！', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (400, 'Database shows', '데이터베이스 표시', '資料庫顯示', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (401, 'Actual content', '실제 콘텐츠', '實際內容', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (402, 'Image', '이미지', '圖片', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (403, 'Actual Usage Status', '실제 사용 상태', '實際使用狀態', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (404, 'Found in posts', '게시물에서 발견됨', '在文章中找到', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (405, 'DB Status', 'DB 상태', '資料庫狀態', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (406, 'Update needed?', '업데이트 필요?', '需要更新？', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (407, 'Error checking usage', '사용 여부 확인 오류', '檢查使用狀況錯誤', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (408, 'Image not found', '이미지를 찾을 수 없음', '找不到圖片', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (409, 'Usage status updated successfully', '사용 상태가 성공적으로 업데이트되었습니다', '使用狀態已成功更新', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (410, 'Error updating usage status', '사용 상태 업데이트 오류', '更新使用狀態錯誤', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (411, 'Checking usage...', '사용 여부 확인 중...', '檢查使用狀況中...', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (412, 'Checking actual usage in content...', '콘텐츠에서 실제 사용 여부 확인 중...', '檢查內容中的實際使用狀況...', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (413, 'Database Status', '데이터베이스 상태', '資料庫狀態', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (414, 'Actual Usage', '실제 사용', '實際使用', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (415, 'Found in Boards', '게시판에서 발견됨', '在版面中找到', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (416, 'Updated!', '업데이트됨!', '已更新！', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (417, 'Failed to update usage status', '사용 상태 업데이트 실패', '更新使用狀態失敗', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (418, 'An error occurred while updating usage status', '사용 상태 업데이트 중 오류 발생', '更新使用狀態時發生錯誤', 'sitemanager.files.editor-images');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (419, 'Post Not Found', '게시물을 찾을 수 없습니다', '找不到文章', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (420, 'Highlight Images', '이미지 강조', '強調圖片', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (421, 'This post contains no images.', '이 게시물에는 이미지가 없습니다.', '此文章不包含圖片。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (422, 'Board Attachments Management', '게시판 첨부파일 관리', '版面附件管理', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (423, 'Unknown', '알 수 없음', '未知', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (424, 'Unknown Post', '알 수 없는 게시물', '未知文章', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (425, 'Are you sure you want to delete this attachment?', '이 첨부파일을 삭제하시겠습니까?', '確定要刪除此附件嗎？', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (426, 'No board attachments found.', '게시판 첨부파일이 없습니다.', '沒有找到版面附件。', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (427, 'Replace Attachment', '첨부파일 교체', '替換附件', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (428, 'Replace file', '파일 교체', '替換檔案', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (429, 'Choose new file', '새 파일 선택', '選擇新檔案', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (430, 'Max file size: 50MB', '최대 파일 크기: 50MB', '最大檔案大小：50MB', 'sitemanager.files.board-attachments');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (431, 'Replace', '교체', '替換', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (432, 'Trace Mode', '추적 모드', '追蹤模式', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (433, 'Clear Locations', '위치 정보 삭제', '清除位置', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (434, 'translation_trace_enabled', '번역 추적이 활성화되었습니다.', '翻譯追蹤已啟用', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (435, 'translation_trace_disabled', '번역 추적이 비활성화되었습니다.', '翻譯追蹤已停用', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (436, 'confirm_clear_all_locations', '모든 위치 정보를 삭제하시겠습니까?', '確定要清除所有位置信息嗎？', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (437, 'all_locations_cleared', '모든 위치 정보가 삭제되었습니다.', '所有位置信息已清除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (438, 'Failed to clear locations', '위치 정보 삭제에 실패했습니다.', '清除位置信息失敗', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (439, 'Error occurred while clearing locations', '위치 정보 삭제 중 오류가 발생했습니다.', '清除位置信息時發生錯誤', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (440, 'Are you sure you want to clear all location information?', '모든 위치 정보를 삭제하시겠습니까?', '確定要清除所有位置信息嗎？', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (441, 'All location information has been cleared. Please navigate through the site to collect new location data.', '모든 위치 정보가 삭제되었습니다. 새로운 위치 데이터를 수집하려면 사이트를 탐색해주세요.', '所有位置信息已清除。請瀏覽網站以收集新的位置數據。', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (442, 'Failed to toggle trace mode', '추적 모드 전환에 실패했습니다.', '切換追蹤模式失敗', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (443, 'Error occurred while toggling trace mode', '추적 모드 전환 중 오류가 발생했습니다.', '切換追蹤模式時發生錯誤', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (444, 'No Location', '위치 정보 없음', '無位置信息', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (445, 'Trace mode updated successfully', '추적 모드가 성공적으로 업데이트되었습니다.', '追蹤模式已成功更新', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (446, 'All locations cleared successfully', '모든 위치 정보가 성공적으로 삭제되었습니다.', '所有位置信息已成功清除', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (447, 'Language trace enabled', '언어 추적이 활성화되었습니다.', '語言追蹤已啟用', 'sitemanager.languages.toggle-trace');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (448, 'Language trace disabled', '언어 추적이 비활성화되었습니다.', '語言追蹤已停用', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (449, '.env file not found', '.env 파일을 찾을 수 없습니다.', '找不到 .env 文件', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (450, 'Error updating trace mode', '추적 모드 업데이트 중 오류가 발생했습니다.', '更新追蹤模式時發生錯誤', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (451, 'All location information cleared', '모든 위치 정보가 삭제되었습니다.', '所有位置信息已清除', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (452, 'Location', '위치', '位置', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (453, 'Enter location (comma-separated)', '위치를 입력하세요 (쉼표로 구분)', '輸入位置（以逗號分隔）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (454, 'Use comma to separate multiple locations', '여러 위치는 쉼표로 구분하세요', '使用逗號分隔多個位置', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (455, 'Add location', '위치 추가', '添加位置', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (456, 'Edit location', '위치 편집', '編輯位置', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (457, 'Enter location', '위치 입력', '輸入位置', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (458, 'Location saved successfully', '위치가 성공적으로 저장되었습니다.', '位置已成功保存', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (459, 'Error saving location', '위치 저장 중 오류가 발생했습니다.', '保存位置時發生錯誤', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (461, 'Cannot determine current page location', '현재 페이지 위치를 확인할 수 없습니다', '無法確定當前頁面位置', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (462, 'Unable to identify the current page location', '현재 페이지 위치를 식별할 수 없습니다', '無法識別當前頁面位置', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (463, 'Clear Current Page Location', '현재 페이지 위치 삭제', '清除當前頁面位置', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (464, 'Are you sure you want to clear location information for', '다음 위치의 정보를 삭제하시겠습니까:', '確定要清除以下位置的信息嗎：', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (465, 'Yes, clear it', '네, 삭제합니다', '是的，清除它', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (466, 'Location Cleared', '위치 정보 삭제됨', '位置信息已清除', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (467, 'Failed to clear location', '위치 삭제에 실패했습니다', '清除位置失敗', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (468, 'An error occurred while clearing location', '위치 삭제 중 오류가 발생했습니다', '清除位置時發生錯誤', 'sitemanager.languages.index,sitemanager.members.index,sitemanager.members.edit,sitemanager.members.create,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (469, 'Current page location not found', '현재 페이지 위치를 찾을 수 없습니다', '找不到當前頁面位置', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (470, 'Current page location cleared from', '현재 페이지 위치가 다음에서 삭제됨:', '當前頁面位置已從以下位置清除：', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (471, 'keys', '개 키', '個鍵', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (472, 'Error clearing current page locations', '현재 페이지 위치 삭제 중 오류 발생', '清除當前頁面位置時發生錯誤', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (473, 'Search by key, translation, or location...', '키, 번역, 또는 위치로 검색...', '按鍵、翻譯或位置搜尋...', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (474, 'Filter by location...', '위치로 필터링...', '按位置篩選...', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (475, 'Filtered', '필터됨', '已篩選', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (476, 'Search (Press Enter)', '검색 (엔터키 누르기)', '搜尋（按 Enter 鍵）', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (477, 'Clear all filters', '모든 필터 지우기', '清除所有篩選', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (478, 'Press Enter to search', '엔터키를 눌러 검색', '按 Enter 搜索', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (479, 'Select from suggestions or press Enter to search', '제안에서 선택하거나 엔터키를 눌러 검색', '從建議中選擇或按 Enter 搜索', 'sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (480, 'Clear current page language location information', '현재 페이지 언어 위치 정보 삭제', '清除當前頁面語言位置信息', 'sitemanager.languages.index,sitemanager.groups.index,sitemanager.files.editor-images,sitemanager.boards.index,sitemanager.boards.edit,sitemanager.files.board-attachments,sitemanager.dashboard,sitemanager.comments.index,sitemanager.menus.index,sitemanager.settings');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (481, 'Regular Member', '일반 회원', '一般會員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (482, 'Board Manager', '게시판 관리자', '版面管理員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (483, 'Moderator', '운영자', '版主', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (484, 'Administrator', '관리자', '管理員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (485, 'Root Administrator', '최고 관리자', '超級管理員', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (486, 'Custom Level', '사용자 정의 레벨', '自定義等級', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (487, 'Basic User', '기본 사용자', '基本用戶', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (488, 'Pagination Navigation', '페이지 네비게이션', '分頁導航', 'sitemanager.files.editor-images,sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (489, 'Showing', '표시 중', '顯示', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (490, 'to', '에서', '到', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (491, 'of', '의', '共', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (492, 'results', '결과', '結果', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (493, 'Per page', '페이지당', '每頁', 'sitemanager.files.editor-images,sitemanager.languages.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (494, 'Attachments', '첨부파일', '附件', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (495, 'Recent Posts', '최근 게시글', '最新文章', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (496, 'Recent Comments', '최근 댓글', '最新評論', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (497, 'No comments yet.', '아직 댓글이 없습니다.', '尚無評論。', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (498, 'Board Statistics', '게시판 통계', '版面統計', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (499, 'Last Post', '최근 게시물', '最新文章', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (500, 'Manage Translations', '번역 관리', '翻譯管理', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (501, 'Recent Files', '최근 파일', '最新檔案', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (502, 'No files uploaded yet.', '아직 업로드된 파일이 없습니다.', '尚未上傳檔案。', 'sitemanager.dashboard');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (503, 'Back to Boards List', '게시판 목록으로 돌아가기', '返回版面列表', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (504, 'Select Board', '게시판 선택', '選擇版面', 'sitemanager.comments.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (506, 'Update Search Content', '검색 콘텐츠 업데이트', '更新搜索內容', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (507, 'This will extract text content from all menu-linked view files and update search database. Continue?', '모든 메뉴 연결 뷰 파일에서 텍스트 콘텐츠를 추출하여 검색 데이터베이스를 업데이트합니다. 계속하시겠습니까?', '這將從所有菜單連結的視圖文件中提取文本內容並更新搜索資料庫。繼續嗎？', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (508, 'Extracting content from view files and updating search database.', '뷰 파일에서 콘텐츠를 추출하고 검색 데이터베이스를 업데이트하는 중입니다.', '正在從視圖文件中提取內容並更新搜索資料庫。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (509, 'Search content update failed.', '검색 콘텐츠 업데이트에 실패했습니다.', '搜索內容更新失敗。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (510, 'An error occurred during search content update.', '검색 콘텐츠 업데이트 중 오류가 발생했습니다.', '搜索內容更新期間發生錯誤。', 'sitemanager.menus.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (511, 'Manage comments', '댓글 관리', '管理評論', 'sitemanager.boards.index');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (512, 'No posts yet.', '아직 게시물이 없습니다.', '尚無文章。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (513, 'No boards created yet.', '아직 게시판이 생성되지 않았습니다.', '尚未建立任何版塊。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (514, 'Extensions', '확장', '擴展', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (515, 'Inquiries', '문의', '諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (516, 'Registrations', '등록', '報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (517, 'Payments', '결제', '付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (518, 'Search...', '검색...', '搜尋...', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (519, 'Registered', '등록됨', '已報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (520, 'Expired', '만료됨', '已過期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (521, 'Cancelled', '취소됨', '已取消', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (522, 'Program', '프로그램', '課程', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (523, 'Are you sure?', '정말 삭제하시겠습니까?', '確定嗎？', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (524, 'All Payment Status', '전체 결제 상태', '所有付款狀態', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (525, 'Deposit Paid', '보증금 완료', '已付訂金', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (526, 'Fully Paid', '전액 결제', '已全額付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (527, 'Refunded', '환불됨', '已退款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (528, 'Course', '코스', '課程', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (529, 'Start Date', '시작일', '開始日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (530, 'Payment Status', '결제 상태', '付款狀態', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (531, 'Completed', '완료', '已完成', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (532, 'Failed', '실패', '失敗', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (533, 'All Types', '전체 유형', '所有類型', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (534, 'Deposit', '보증금', '訂金', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (535, 'Balance', '잔액', '餘額', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (536, 'Full', '전체', '全額', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (537, 'Refund', '환불', '退款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (538, 'Registration', '등록', '報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (539, 'Amount', '금액', '金額', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (540, 'Provider', '결제사', '付款方式', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (541, 'Paid', '결제됨', '已付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (542, 'transactions', '거래', '交易', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (543, 'Total Posts', '총 게시물', '總文章數', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (544, 'Recent Inquiries', '최근 문의', '最近諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (545, 'Date', '날짜', '日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (546, 'Recent Registrations', '최근 등록', '最近報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (547, 'Payment', '결제', '付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (548, 'Recent Payments', '최근 결제', '最近付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (549, 'Customer', '고객', '客戶', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (550, 'Custom Route Target', '사용자 정의 경로 대상', '自訂路由目標', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (551, 'If the automatic route filtering does not work correctly, you can manually specify the target path here. This will override the selected route above.', '자동 경로 필터링이 제대로 작동하지 않는 경우 여기에 대상 경로를 수동으로 지정할 수 있습니다. 이 설정은 위에서 선택한 경로를 무시합니다.', '如果自動路由過濾無法正常運作，您可以在此手動指定目標路徑。此設定將覆蓋上方選擇的路由。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (552, 'Example', '예시', '範例', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (553, 'Search Content', '검색 콘텐츠', '搜尋內容', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (554, 'Content for search indexing. Leave empty to auto-extract from view file.', '검색 색인용 콘텐츠입니다. 뷰 파일에서 자동 추출하려면 비워두세요.', '用於搜尋索引的內容。留空則從視圖檔案自動擷取。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (555, 'Optional. Text content used for site search. If empty, it will be automatically extracted from the linked view file.', '선택 사항. 사이트 검색에 사용되는 텍스트 콘텐츠입니다. 비어 있으면 연결된 뷰 파일에서 자동으로 추출됩니다.', '選填。用於網站搜尋的文字內容。如為空白，將從連結的視圖檔案自動擷取。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (556, 'This route supports custom menu ID. You can use the route name (', '이 경로는 사용자 정의 메뉴 ID를 지원합니다. 경로 이름(', '此路由支援自訂選單 ID。您可以使用路由名稱（', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (557, ') or specify a custom path like ', ')을 사용하거나 다음과 같은 사용자 정의 경로를 지정할 수 있습니다 ', '）或指定自訂路徑如 ', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (558, 'Custom Menu ID Support', '사용자 정의 메뉴 ID 지원', '自訂選單 ID 支援', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (559, 'Use route name', '경로 이름 사용', '使用路由名稱', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (560, '(default behavior)', '(기본 동작)', '（預設行為）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (561, 'Use custom path', '사용자 정의 경로 사용', '使用自訂路徑', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (562, '(for team-specific menus)', '(팀별 메뉴용)', '（用於團隊特定選單）', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (563, 'Route pattern', '경로 패턴', '路由模式', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (564, 'Board Connected & URI Updated', '게시판 연결 및 URI 업데이트됨', '版塊已連結並更新 URI', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (565, 'Target automatically updated to', '대상이 자동으로 업데이트됨', '目標已自動更新為', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (566, 'This provides better performance by avoiding database queries.', '이렇게 하면 데이터베이스 쿼리를 피하여 더 나은 성능을 제공합니다.', '這可避免資料庫查詢，提供更好的效能。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (567, 'Please select a route first.', '먼저 경로를 선택하세요.', '請先選擇路由。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (568, 'Current', '현재', '目前', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (569, 'Using custom path', '사용자 정의 경로 사용 중', '使用自訂路徑', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (570, 'View', '보기', '查看', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (571, 'Are you sure you want to delete this item?', '이 항목을 삭제하시겠습니까?', '確定要刪除此項目嗎？', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (572, 'Inquiry Details', '문의 상세', '諮詢詳情', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (573, 'Details', '상세', '詳情', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (574, 'Full Name', '이름', '姓名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (575, 'Country', '국가', '國家', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (576, 'Program Interest', '관심 프로그램', '感興趣的課程', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (577, 'Message', '메시지', '訊息', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (578, 'Updated At', '수정일', '更新時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (579, 'Token Expires At', '토큰 만료일', '令牌過期時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (580, 'Related Registration', '관련 등록', '相關報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (581, 'Edit Registration', '등록 수정', '編輯報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (582, 'Edit Item', '항목 수정', '編輯項目', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (583, 'Inquiry id', '문의 ID', '諮詢 ID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (584, 'First name', '이름', '名字', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (585, 'Last name', '성', '姓氏', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (586, 'Phone country', '전화 국가번호', '電話國碼', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (587, 'Date of birth', '생년월일', '出生日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (588, 'Nationality', '국적', '國籍', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (589, 'Current city', '현재 도시', '目前城市', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (590, 'Current state', '현재 주/도', '目前州/省', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (591, 'Interested course', '관심 코스', '感興趣的課程', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (592, 'Preferred start date', '희망 시작일', '期望開始日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (593, 'Duration weeks', '수업 기간(주)', '課程週數', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (594, 'Korean level', '한국어 수준', '韓語程度', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (595, 'Accommodation required', '숙소 필요', '需要住宿', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (596, 'Room type', '방 유형', '房型', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (597, 'Accommodation weeks', '숙소 기간(주)', '住宿週數', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (598, 'Airport pickup', '공항 픽업', '機場接送', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (599, 'Arrival date', '도착일', '抵達日期', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (600, 'Arrival time', '도착 시간', '抵達時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (601, 'Flight number', '항공편 번호', '航班號碼', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (602, 'Promotion code', '프로모션 코드', '優惠碼', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (603, 'Special requests', '특별 요청', '特殊需求', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (604, 'Terms agreed', '이용약관 동의', '同意條款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (605, 'Privacy agreed', '개인정보 동의', '同意隱私權政策', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (606, 'Marketing agreed', '마케팅 동의', '同意行銷', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (607, 'Total amount', '총 금액', '總金額', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (608, 'Deposit amount', '보증금 금액', '訂金金額', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (609, 'Edm synced', 'EDM 동기화', 'EDM 同步', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (610, 'Edm student id', 'EDM 학생 ID', 'EDM 學生 ID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (611, 'Edm synced at', 'EDM 동기화 일시', 'EDM 同步時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (612, 'Registration Details', '등록 상세', '報名詳情', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (613, 'Uuid', 'UUID', 'UUID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (614, 'Payment History', '결제 내역', '付款記錄', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (615, 'Related Inquiry', '관련 문의', '相關諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (616, 'View Inquiry', '문의 보기', '查看諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (617, 'View Registration', '등록 보기', '查看報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (618, 'View Payment', '결제 보기', '查看付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (619, 'Personal Information', '개인 정보', '個人資料', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (620, 'Course Information', '코스 정보', '課程資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (621, 'Accommodation', '숙소', '住宿', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (622, 'Payment Information', '결제 정보', '付款資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (623, 'Additional Information', '추가 정보', '其他資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (624, 'Payment Details', '결제 상세', '付款詳情', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (625, 'Transaction ID', '거래 ID', '交易 ID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (626, 'View Full Registration', '전체 등록 보기', '查看完整報名', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (627, 'Original Inquiry', '원본 문의', '原始諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (628, 'Provider Information', '결제사 정보', '付款方式資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (629, 'Currency', '통화', '貨幣', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (630, 'Paid at', '결제일', '付款時間', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (631, 'Provider transaction id', '결제사 거래 ID', '付款方式交易 ID', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (632, 'View All Payments', '전체 결제 보기', '查看所有付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (633, 'Registration updated successfully.', '등록이 성공적으로 수정되었습니다.', '報名已成功更新。', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (634, 'payment(s)', '건 결제', '筆付款', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (635, 'Inquiry', '문의', '諮詢', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (636, 'Contact Information', '연락처 정보', '聯繫資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (637, 'Tracking Information', '추적 정보', '追蹤資訊', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (638, 'IP Address', 'IP 주소', 'IP 位址', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (639, 'User Agent', '사용자 에이전트', '使用者代理', '');
INSERT INTO languages (id, `key`, ko, tw, location) VALUES (640, 'Registration ID', '등록 ID', '報名 ID', '');
